name: ol_driving_license_management_ui
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  file_picker: ^10.3.1
  dio: ^5.0.0

  ol_driving_license_management_widgets:
    path: ../ol_driving_license_management_widgets
  ol_driving_license_management_providers:
    path: ../ol_driving_license_management_providers
  ol_driving_license_management_dto:
    path: ../ol_driving_license_management_dto
  my_widgets:
    path: ../my_widgets

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1   # ğŸ“Œ Ù„Ø¥Ø¹Ø¯Ø§Ø¯ Ø§Ù„Ø£ÙŠÙ‚ÙˆÙ†Ø§Øª

flutter_icons:
  android: true
  ios: true
  windows: true
  image_path: "assets/app_icon/driver_license_icon.png"

flutter:
  uses-material-design: true

  # Ø¥Ø°Ø§ Ø¨Ø¯Ùƒ ØªØ³ØªØ¹Ù…Ù„ Ø£ØµÙˆÙ„ (ØµÙˆØ± ÙˆØºÙŠØ±Ù‡):
  assets:
    - assets/app_icon/driver_license_icon.png

  # Ø¥Ø°Ø§ Ø¹Ù†Ø¯Ùƒ Ø®Ø·ÙˆØ· Ù…Ø®ØµØµØ©ØŒ Ø¶ÙŠÙÙ‡Ø§ Ù‡ÙˆÙ†
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic