name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - run: git config --global --add safe.directory '*'

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b stable
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      - name: Flutter Version
        run: flutter --version

      - name: Upgrade Flutter packages
        run: flutter pub upgrade
        working-directory: ol_driving_license_management_ui

      - name: Get Dependencies
        run: flutter pub get
        working-directory: ol_driving_license_management_ui

      # ðŸ‘‡ Ù‡Ø°Ù‡ Ø§Ù„Ø®Ø·ÙˆØ© Ø§Ù„Ù…Ù‡Ù…Ø© Ø¹Ø´Ø§Ù† Ø§Ù„Ø£ÙŠÙ‚ÙˆÙ†Ø©
      - name: Generate app icons
        run: flutter pub run flutter_launcher_icons
        working-directory: ol_driving_license_management_ui

      - name: Build APK
        run: flutter build apk --release
        working-directory: ol_driving_license_management_ui

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: ol_driving_license_management_ui/build/app/outputs/flutter-apk/app-release.apk